### PR TITLE
Merging this repo with the greenland master branch

### PR DESCRIPTION
**Pull request by ingram1107**
Currently working on merging two branches

### TODO

- [x] Catch possible errors
~~- [ ] Graceful error handling in socket connection~~
- [x] Display main menu in client (partial)
- [x] Response to the request of client in server
- [x] Compile with Makefile
- [x] Modularise client and server

### CODE REVIEW

**Comment by ingram1107** [comment]
Pretty much done, ready to merge

**Comment by ngzhekai** [comment]
Should I do a sync instead of merging? Cause it shows the branch has conflicts.

**Comment by ingram1107** [comment]
U can just fix it on the GitHub or git pull on ur local machine and fix it with ur git client

**Comment by ingram1107** [comment]
conflicts resolved

**Review by ngzhekai — APPROVED** [review]

**Pull request merged**
